### ISSUE TITLE
Adding radius other than 1' does not work in proximity constraint of Imaging and Spectro search tools

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#119]
Changing the radius setting does work, even when we erase the radius column in the (RA,Dec,radius) default list.

**Comment by mtaghiza** [comment]
Fixed.

**Comment by raddick** [comment]
Looks like this is still an issue when you select "All Nearby Objects." The query is constructed with 1.0 as the radius value, no matter what you select from the form, and the results are always the same.  Screenshot of the query/results page:

<img width="949" alt="untitled-16" src="https://cloud.githubusercontent.com/assets/1709156/10607856/60834870-770a-11e5-9752-d7a511c57158.png">

**Comment by mtaghiza** [comment]
It is working properly. What happens is that you have to remove the "sep" column from the input coordinate file or text in order for the "radius" input to be considered. Please retest and close.

**Comment by mtaghiza** [comment]
Confirmed fix as of prod version sciserver-v1.8.1. Closing...
