### ISSUE TITLE
Retrieving all columns does not work in imaging query form

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#34]
Test: s_imaging_query_form_12
After selecting all items in the imaging menu, no page is shown and throws an error instead

**Comment by mtaghiza** [comment]
Happened because the request string becomes much longer than what the maximum default value is in SkySeverWS. Created an issue there and fixed it.
Closing...

**Comment by raddick** [comment]
This appears to not be working in skyserver_v1_2_0 .

Go to the Imaging Query Form:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/IQS.aspx

In the imaging menu (under "Parameters to Return"), click on airmass_g and use shift-click to select everything down to z. Click Submit Request.

It returns an error saying "Query did not return results successfully, check input and try again later."

Reopening issue.

**Comment by mtaghiza** [comment]
Works right now in the dev version. Will see why it does not work on test.

**Comment by raddick** [comment]
Working on scidev03 manu version but not on test

**Comment by mtaghiza** [comment]
Works on dev, should be working on test after the next release.

**Comment by raddick** [comment]
Still not working in sciserver_v1_4_0 . Now gives an error page with a message saying "An error occurred".

**Comment by mtaghiza** [comment]
This is probably a problem with the proxy (IIS) settings in scisever04, that might be having problems handling long URIs. (the URI is long since all the column names are written as request parameters.
It works on scidev03, since trhe proxy sunning in sciserver03 is another one (nginx). Will have to see how this behaves with the replacement proxy (HAproxy) that is going to be installed by Jan in a few days.

**Comment by raddick** [comment]
Has Jan installed the replacement HAProxy yet? Can we test this? @mtaghiza ?

**Comment by mtaghiza** [comment]
works now under test.preprod. Please test and confirm.

**Comment by mtaghiza** [comment]
Just tested in version sciserver-v1.8.1. Issue is fixed. Closing issue...
